### ISSUE TITLE
wf_extendedBreadcrumb not working correctly on Contao 3.2.x

### ISSUE THREAD

**Issue by chrizzbee** [menatwork-ia/wf_extendedBreadcrumb#1]
NEWS ITEM ISSUE
The breadcrumb extension seems not to be working correctly on news items on Contao 3.2.x. Only up to the newsreader page the path is rendered. No news items are shown after the newsreader page. An example news item "My News" would show up like this in the breadcrumb trail:

Home > News > Newsreader >

"Newsreader" is rendered as link, despite it has the class "last" applied plus a delimiter is added.

HIDE IN EXTENDED BREADCRUMB TRAIL ISSUE
In the page layout one can select to hide the page in the extended breadcrumb trail. This seems not to be working. Wether or not the checkbox is selected, it has no affect on the page shown in the breadcrumb trail.

**Comment by stefanheimes** [comment]
Hi, the first point isn't a bug at all. The breadcrumb can't resolve the auto_item. So you have to add this logic. We have a hook for this. See
https://github.com/menatwork-ia/wf_extendedBreadcrumb/blob/master/system/modules/wf_extendedBreadcrumb/wf_extendedBreadcrumb.php#L437

**Comment by stefanheimes** [comment]
Hi, i can't reproduce this bug. The only page which is not hideable is the current active page. This page can't hide in the breadcrumb. For all other pages, i have no problems to remove these from the list.

**Comment by chrizzbee** [comment]
better no bug than a bug :-) sorry didn't know about the auto-item. and now also the hiding in the trail makes sense. never mind! thanks anyway.

**Comment by stefanheimes** [comment]
You are welcome.
